from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import PostViewSet, CommentViewSet

# Initialize the router
router = DefaultRouter()

# Register the Post and Comment viewsets with the router
router.register(r'posts', PostViewSet)
router.register(r'comments', CommentViewSet)

# Define the urlpatterns
urlpatterns = [
    # Include the URLs generated by the router
    path('', include(router.urls)),
]
